# resolution, caption_extension, batch_size, enable_bucket, bucket_no_upscale must be set in either general or datasets
# general configurations
[general]
resolution = [1280, 1280]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = true

# [[datasets]]
# image_directory = "./train/hhct_restaurant/hhct/ruined"
# cache_directory = "./train/hhct_restaurant/hhct/ruined/cache_qwen_image"
# num_repeats = 4

# [[datasets]]
# image_directory = "./train/hhct_restaurant/hhct/ruined_split41"
# cache_directory = "./train/hhct_restaurant/hhct/ruined_split41/cache_qwen_image"
# num_repeats = 4

# [[datasets]]
# image_directory = "./train/hhct_restaurant/hhct/complete"
# cache_directory = "./train/hhct_restaurant/hhct/complete/cache_qwen_image"
# num_repeats = 4

[[datasets]]
image_directory = "./train/hhct_restaurant/hhct/complete_split41"
cache_directory = "./train/hhct_restaurant/hhct/complete_split41/cache_qwen_image"
num_repeats = 4
